[theme]
primaryColor = "#e8c042"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
textColor = "#494646"
font = "sans serif"

[theme.sidebar]
backgroundColor = "#ececec"
secondaryBackgroundColor = "#e4e3e3"
textColor = "#494646"
borderColor = "#d19e40"

[server]
headless = true
